apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bootcamp2
type: Opaque
stringData:
  password: "BootcampPass123"
  database-url: "postgresql://taskuser:BootcampPass123@postgres-service:5432/taskdb"